eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #使用jdbc的getGeneratedKeys获取数据库自增主键值
    use-generated-keys: true
    #使用列标签替换列别名 默认：true
    use-column-label: true
    #开启驼峰命名转换：Table(create_time) -> Entity(createTime)
    map-underscore-to-camel-case: true