server:
  port: 8082
  servlet:
    context-path:

spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  config-location: classpath:mybatis-config.xml
  #  type-aliases-package: com.example.domain
  configuration:
    #使用jdbc的getGeneratedKeys获取数据库自增主键值
    use-generated-keys: true
    #使用列标签替换列别名 默认：true
    use-column-label: true
    #开启驼峰命名转换：Table(create_time) -> Entity(createTime)
    map-underscore-to-camel-case: true
#mapper:
#    mapper:
#        - tk.mybatis.springboot.util.MyMapper
#    not-empty: false
#    identity: MYSQL
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
